# DOCUMENTATION: https://learn.getgrav.org/17/basics/grav-configuration
# PRD SETTINGS: https://learn.getgrav.org/17/security/configuration

assets:
  # depending on asset size HTTTP/2 may be a better option
  css_pipeline: true   # concat from assets.addCss
  # do not enable (breaking change until skel.js is removed)
  js_pipeline: false    # concat from assets.addJs

# Enable force_ssl if env supports it
force_ssl: false       # Use HTTPS only (redirect from HTTP -> HTTPS)

debugger:
  enabled: false      # disable development helper, if set

session:
  initialize: false   # Disables "cookies": GDPR-compliance for visitors
  # Enable secure if env supports it
  secure: false       # Use this as your site should be using HTTPS only
  httponly: true      # Protects session cookies against client side scripts and XSS
  samesite: Strict    # Prevent all cross-site scripting attacks
  split: true         # Separate admin session from the site session for added security

cache:
  enabled: true       # Greatly speeds up the site
  check:
    method: hash      # Optimization, disables file modification checks for pages
  driver: auto        # auto|file|apc|xcache|memcache|wincache|redis
  lifetime: 57600     # 0 = infinite / 2419200 = 1 month / 604800 = 7 days / 57600 = 16 hours / 36000 = 10 hours
  prefix: 'g'         # prevent cache conflicts
  gzip: true          # compress files
  allow_webserver_gzip: true # set headers

images:
  default_image_quality: 100  # assume images are already optimized
  cache_all: false            # do not cache images
  debug: false                # disabled
  defaults:
    loading: auto             # Let browser pick: auto, lazy or eager (Grav 1.7+)

twig:
  cache: true         # Greatly speeds up the site
  debug: false        # We do not want to display debug messages
  auto_reload: false  # Optimization, disables file modification checks for twig files
  autoescape: true    # Protects from many XSS attacks, but requires twig updates if used in older sites/themes/plugins

errors:
  display: 0          # Display only a simple error
  log: true           # Log errors for later inspection

debugger:
  enabled: false      # Never keep debugger enabled in a live site.
  censored: true      # In case if you happen to enable debugger, avoid displaying sensitive information

strict_mode:          # Test your site before changing these. Removes backward compatibility and improves site security.
  yaml_compat: false
  twig_compat: false
  blueprint_compat: false
