title: 'Oxygen'
# html lang only
default_lang: 'en'
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
